name: Pipeline CI/CD

on:
  push:
    branches:
      - main
      - pipeline-setup

jobs:
  Workflow_Inicial:
    name: Configurar Workflow Inicial
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Workflow Inicial
        uses: actions/checkout@v3

  SCA:
    name: Análisis SCA con Dependency Check
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Descargar Dependency Check
        run: |
          curl -L --retry 3 --max-time 60 -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v11.1.1/dependency-check-11.1.1-release.zip

      - name: Descomprimir Dependency Check
        run: |
          unzip dependency-check.zip -d dependency-check
          ls -la dependency-check

      - name: Ejecutar análisis SCA
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          dependency-check/dependency-check/bin/dependency-check.sh --project "CarlaH-laboratorio-final" \
          --scan ./ --format ALL --out ./sca-report \
          --failOnCVSS 4.0 \
          --nvdApiKey ${{ secrets.NVD_API_KEY }}

      - name: Subir reporte como artefacto
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: sca-report
          path: ./sca-report/*
      
      - name: Verificar los archivos generados
        run: ls -R ./sca-report

  Image_Security:
    name: Análisis de Seguridad de Imagen Docker con Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Clonar código fuente
        uses: actions/checkout@v3

      - name: Construir Imagen Docker
        run: |
          docker build --no-cache -t my-app:latest -f Dockerfile .

      - name: Verificar Imagen Docker
        run: |
          docker images my-app:latest

      - name: Check Alpine version
        run: docker run --rm my-app:latest cat /etc/os-release
        

      - name: Verificar si Docker está corriendo
        run: |
          docker info

      - name: Dar permisos a Docker
        run: |
          sudo usermod -aG docker $USER
          newgrp docker

      - name: Instalar Trivy
        run: |
          wget -qO- https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | bash
          sudo mv ./bin/trivy /usr/local/bin/trivy

      - name: Verificar instalación de Trivy
        run: |
          /usr/local/bin/trivy --version

      - name: Ejecutar análisis de seguridad
        run: |
          mkdir -p ./trivy-report
          /usr/local/bin/trivy image --scanners vuln --severity CRITICAL,HIGH,MEDIUM --exit-code 1 --no-progress --format json --output ./trivy-report/trivy-report.txt my-app:latest

      - name: Verificar los archivos generados
        run: |
          echo "Archivos en ./trivy-report:"
          ls -la ./trivy-report

      - name: Subir reporte como artefacto
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: ./trivy-report/*

  deploy:
    name: Despliegue de la Aplicación
    runs-on: ubuntu-latest
    steps:
      - name: Subir Imagen a Docker Hub
        run: |
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          docker tag my-app:latest ${DOCKER_USERNAME}/my-app:latest
          docker push ${DOCKER_USERNAME}/my-app:latest

      - name: Verificar login a Docker
        run: docker info

      - name: Extraer imagen desde Docker Hub
        run: |
          docker pull ${DOCKER_USERNAME}/my-app:latest

      - name: Desplegar aplicación
        run: |
          docker run -d --name my-app -p 8080:8080 ${DOCKER_USERNAME}/my-app:latest