name: Pipeline CI/CD

on:
  push:
    branches:
      - main
      - pipeline-setup

jobs:
  Workflow_Inicial:
    name: Configurar Workflow Inicial
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Workflow Inicial
        uses: actions/checkout@v3

  SCA:
    name: An치lisis SCA con Dependency Check
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Descargar Dependency Check
        run: |
          curl -L --retry 3 --max-time 60 -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v11.1.1/dependency-check-11.1.1-release.zip

      - name: Descomprimir Dependency Check
        run: |
          unzip dependency-check.zip -d dependency-check
          ls -la dependency-check

      - name: Ejecutar an치lisis SCA
        run: |
          dependency-check/dependency-check/bin/dependency-check.sh --project "CarlaH-laboratorio-final" \
          --scan ./ --format ALL --out ./sca-report \
          --failOnCVSS 4.0

      - name: Subir reporte como artefacto
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: sca-report
          path: ./sca-report/*
      
      - name: Verificar los archivos generados
        run: ls -R ./sca-report

  Build_DockerImage:
    name: Construcci칩n de la imagen Docker
    runs-on: ubuntu-latest
    steps:
      - name: Clonar c칩digo fuente
        uses: actions/checkout@v3
        
      - name: Construir Imagen Docker
        run: |
          docker build -t my-app:latest .